## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
   - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - julia -e 'mit = "ModuleInterfaceTools"; mh3 = "MurmurHash3"; loc = "https://github.com/JuliaString"; la = ("StrAPI", "CharSetEncodings", "ChrBase"); if VERSION < v"0.7.0-DEV.5183"; Pkg.clone("$loc/$mit.jl"); Pkg.clone("$loc/$mh3.jl"); for n in la; Pkg.add(n); end; Pkg.clone(pwd()); else; using Pkg; cln(a) = Pkg.add("$loc/$a.jl"); cln(mit); cln(mh3); for n in la; cln(n); end; end; Pkg.test("StrBase"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("StrBase")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("StrBase")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
