[[CharSetEncodings]]
deps = ["ModuleInterfaceTools", "StrAPI"]
git-tree-sha1 = "3e87f57566ee199db483028418b9847ac6120b10"
repo-rev = ""
repo-url = "https://github.com/JuliaString/CharSetEncodings.jl"
uuid = "cb9422de-a9d8-5b68-86db-ff05833ab307"
version = "0.1.1"

[[ChrBase]]
deps = ["CharSetEncodings", "ModuleInterfaceTools", "Random", "StrAPI"]
git-tree-sha1 = "71a1c9f7510db4b9744d3730f0997974bda95930"
repo-rev = ""
repo-url = "https://github.com/JuliaString/ChrBase.jl"
uuid = "40048718-5f69-11e8-3be1-2f493f2f747a"
version = "0.1.0"

[[ModuleInterfaceTools]]
deps = ["Test"]
git-tree-sha1 = "55585fbfca81ec0e817b2e3fc54fcdcbf3d2a0af"
repo-rev = ""
repo-url = "https://github.com/JuliaString/ModuleInterfaceTools.jl"
uuid = "5cb8414e-7aab-5a03-a681-351269c074bf"
version = "0.1.0+"

[[MurmurHash3]]
git-tree-sha1 = "90e2e709ead7141f6b5d7d863d342cab1d2dcdb4"
repo-rev = ""
repo-url = "https://github.com/JuliaString/MurmurHash3.jl.git"
uuid = "f0d41675-b40b-4ac0-9c24-1938651d8492"
version = "0.1.0"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[StrAPI]]
deps = ["ModuleInterfaceTools", "Random"]
git-tree-sha1 = "561234d811eb16a1c7f6d522a85f63158be65188"
repo-rev = ""
repo-url = "https://github.com/JuliaString/StrAPI.jl"
uuid = "69e7dfc3-c4d0-5e14-8d95-d6042a05b383"
version = "0.1.1"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
