authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Basic functionality for Str types"
keywords = ["Strings"]
license = "MIT"
name = "StrBase"
repo-rev = ""
repo-url = "https://github.com/JuliaString/StrBase.jl.git"
uuid = "9ae48233-fac8-48c3-9111-9059e0a096a8"
version = "0.1.0"

[deps]
CharSetEncodings = "cb9422de-a9d8-5b68-86db-ff05833ab307"
ChrBase = "40048718-5f69-11e8-3be1-2f493f2f747a"
ModuleInterfaceTools = "5cb8414e-7aab-5a03-a681-351269c074bf"
MurmurHash3 = "f0d41675-b40b-4ac0-9c24-1938651d8492"
StrAPI = "69e7dfc3-c4d0-5e14-8d95-d6042a05b383"
