name     = "StrBase"
desc     = "Basic functionality for Str types"
authors  = ["ScottPJones <scottjones@alum.mit.edu>"]
keywords = ["Strings"]
license  = "MIT"
uuid     = "e79e7a6a-7bb1-5a4d-9d64-da657b06f53a"
version = "1.0.0"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

ModuleInterfaceTools = "5cb8414e-7aab-5a03-a681-351269c074bf"
CharSetEncodings = "cb9422de-a9d8-5b68-86db-ff05833ab307"
MurmurHash3 = "b10b62ed-fbae-5ea5-b934-abaf0477b71d"

StrAPI = "69e7dfc3-c4d0-5e14-8d95-d6042a05b383"
ChrBase = "c13fa7b1-fb91-5a40-8b3c-3aad7fd30002"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random  = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]

[compat]
julia = "^1.0.0"
ModuleInterfaceTools = "≥ 1.0.0"
MurmurHash3 = "≥ 1.0.0"
StrAPI = "≥ 1.0.0"
ChrBase = "≥ 1.0.0"
CharSetEncodings = "≥ 1.0.0"
